// Generated by `Web App/spikes/pdf-renderer/generate_fixture.py` — do not hand-edit.
// Shared test data for the PDF-renderer spike (frontend half); the backend half reads
// the sibling sample_fixture.json. Regenerate both by rerunning that script.
import type { SpikeFixture } from './types'

export const sampleFixture: SpikeFixture = {
  "formatVersion": 2,
  "mazeType": "pickaxe",
  "level": "kinder",
  "sheetName": "Kinder July Week 4",
  "year": 2026,
  "month": 7,
  "week": 4,
  "pages": [
    {
      "pageId": "cover",
      "questions": [
        {
          "question_id": "kinder-1star-1",
          "difficulty_star": 1,
          "status": "complete",
          "origin": "manual",
          "maze": {
            "pickaxe_count": 1,
            "width": 3,
            "height": 3,
            "maze": [
              "s_|,_,g_",
              ".,.,.",
              ".,.,."
            ]
          },
          "solutionTrace": "S,1 -> 2(break | wall) -> 3",
          "seeds": {
            "sgSeed": 1001,
            "pathSeed": 2001,
            "wallSeed": 3001
          }
        }
      ]
    },
    {
      "pageId": "page-1",
      "questions": [
        {
          "question_id": "kinder-2star-2",
          "difficulty_star": 2,
          "status": "complete",
          "origin": "manual",
          "maze": {
            "pickaxe_count": 1,
            "width": 3,
            "height": 3,
            "maze": [
              "s_,_|,g_",
              "_,.,.",
              ".,.,."
            ]
          },
          "solutionTrace": "S,1 -> 2 -> 3(break | wall)",
          "seeds": {
            "sgSeed": 1002,
            "pathSeed": 2002,
            "wallSeed": 3002
          }
        },
        {
          "question_id": "kinder-2star-3",
          "difficulty_star": 2,
          "status": "complete",
          "origin": "manual",
          "maze": {
            "pickaxe_count": 1,
            "width": 3,
            "height": 3,
            "maze": [
              "_|,.,.",
              ".,|,g",
              "s,.,."
            ]
          },
          "solutionTrace": "S,7 -> 4 -> 5 -> 6(break | wall)",
          "seeds": {
            "sgSeed": 1003,
            "pathSeed": 2003,
            "wallSeed": 3003
          }
        }
      ]
    },
    {
      "pageId": "page-2",
      "questions": [
        {
          "question_id": "kinder-3star-4",
          "difficulty_star": 3,
          "status": "complete",
          "origin": "manual",
          "maze": {
            "pickaxe_count": 1,
            "width": 4,
            "height": 4,
            "maze": [
              "s,_|,.,.",
              "|,|,.,g",
              "_|,|,_,_",
              ".,|,.,."
            ]
          },
          "solutionTrace": "S,1 -> 2 -> 3(break | wall) -> 7 -> 11 -> 12 -> 8",
          "seeds": {
            "sgSeed": 1004,
            "pathSeed": 2004,
            "wallSeed": 3004
          }
        },
        {
          "question_id": "kinder-4star-5",
          "difficulty_star": 4,
          "status": "complete",
          "origin": "manual",
          "maze": {
            "pickaxe_count": 2,
            "width": 4,
            "height": 4,
            "maze": [
              "|,.,_,.",
              "_,|,.,_",
              "_|,_,|,_",
              "s|,.,|,g"
            ]
          },
          "solutionTrace": "S,13 -> 14(break | wall) -> 15 -> 16(break | wall)",
          "seeds": {
            "sgSeed": 1005,
            "pathSeed": 2005,
            "wallSeed": 3005
          }
        }
      ]
    },
    {
      "pageId": "page-3",
      "questions": [
        {
          "question_id": "kinder-5star-6",
          "difficulty_star": 5,
          "status": "complete",
          "origin": "manual",
          "maze": {
            "pickaxe_count": 2,
            "width": 5,
            "height": 5,
            "maze": [
              "s_|,_|,|,_|,_",
              ".,_,.,_|,g_",
              "_,_|,_|,|,.",
              ".,_|,_,|,.",
              "|,.,.,|,."
            ]
          },
          "solutionTrace": "S,1 -> 6(break _ wall) -> 7 -> 8 -> 9 -> 10(break | wall)",
          "seeds": {
            "sgSeed": 1006,
            "pathSeed": 2006,
            "wallSeed": 3006
          }
        }
      ]
    }
  ]
}
