"""Builds the shared test fixture both renderer spikes render from.

Produces one small `LevelProgress`-shaped sample matching the *future*
`pages: PageRow[]` model from `level_dashboard_pagination_spec.md` §2.1 (not yet
implemented in the real frontend/store — this fixture stands in for what a
finished dashboard would eventually hand to a renderer). pages[0] holds the
1-star tutorial question (feeds the cover page's example maze per
`pdf_export_spec.md` §4.1's cover-row note); pages[1:] are real question rows,
mixing 1-question and 2-question rows and including the sheet's max star (5).

`isBonus` (§4.4, added 2026-08-19) is a manual per-row flag, not computed from
star rating — page-3 (star 5) is hardcoded `True` here purely to keep this
fixture's laurel-wreath page the same one it always was, not because it's the
max star.

Seeds are hardcoded so the fixture is reproducible — re-running this script
regenerates byte-identical mazes. Run from repo root:
    .venv/bin/python "Web App/spikes/pdf-renderer/generate_fixture.py"
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT / "Maze-All-Contents" / "pickaxe-maze-creation"))

from pickaxe_maze.generator import generate_maze  # noqa: E402

SPIKE_DIR = Path(__file__).resolve().parent
FRONTEND_SPIKE_DIR = REPO_ROOT / "Web App" / "frontend" / "src" / "spike"

# (star, sg_seed, path_seed, wall_seed) — fixed for reproducibility.
QUESTIONS = [
    (1, 1001, 2001, 3001),  # tutorial -> pages[0]
    (2, 1002, 2002, 3002),  # page 1
    (2, 1003, 2003, 3003),  # page 1
    (3, 1004, 2004, 3004),  # page 2
    (4, 1005, 2005, 3005),  # page 2
    (5, 1006, 2006, 3006),  # page 3 (max star -> laurel wreath)
]


def build_question(index, star, sg_seed, path_seed, wall_seed):
    result = generate_maze(star=star, sg_seed=sg_seed, path_seed=path_seed, wall_seed=wall_seed)
    return {
        "question_id": f"kinder-{star}star-{index}",
        "difficulty_star": star,
        "status": "complete",
        "origin": "manual",
        "maze": result.maze.to_dict(),
        "solutionTrace": result.solution_trace,
        "seeds": {"sgSeed": result.sg_seed, "pathSeed": result.path_seed, "wallSeed": result.wall_seed},
    }


def main():
    questions = [build_question(i + 1, *q) for i, q in enumerate(QUESTIONS)]

    fixture = {
        "formatVersion": 2,
        "mazeType": "pickaxe",
        "level": "kinder",
        "sheetName": "Kinder July Week 4",
        "year": 2026,
        "month": 7,
        "week": 4,
        "pages": [
            {"pageId": "cover", "questions": [questions[0]], "isBonus": False},
            {"pageId": "page-1", "questions": [questions[1], questions[2]], "isBonus": False},
            {"pageId": "page-2", "questions": [questions[3], questions[4]], "isBonus": False},
            {"pageId": "page-3", "questions": [questions[5]], "isBonus": True},
        ],
    }

    json_path = SPIKE_DIR / "sample_fixture.json"
    json_path.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"wrote {json_path}")

    FRONTEND_SPIKE_DIR.mkdir(parents=True, exist_ok=True)
    ts_path = FRONTEND_SPIKE_DIR / "sampleFixture.ts"
    ts_path.write_text(
        "// Generated by `Web App/spikes/pdf-renderer/generate_fixture.py` — do not hand-edit.\n"
        "// Shared test data for the PDF-renderer spike (frontend half); the backend half reads\n"
        "// the sibling sample_fixture.json. Regenerate both by rerunning that script.\n"
        "import type { SpikeFixture } from './types'\n\n"
        f"export const sampleFixture: SpikeFixture = {json.dumps(fixture, indent=2)}\n"
    )
    print(f"wrote {ts_path}")


if __name__ == "__main__":
    main()
